project:
  type: website
  output-dir: docs

website:
  title: "Max Wall"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - now.qmd
      - blog.qmd
      - notes.qmd
      - cartoons.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute:
  freeze: auto



